### ISSUE TITLE
Impossible to import with Blender 2.67 official

### ISSUE THREAD

**Issue by Spirou4D** [spamandeggs/directX_blender#2]
importing new.x...
Traceback (most recent call last):
  File "C:\Program Files\Blender Foundation\Blender\2.67\scripts\addons_contrib\io_directx_bel\import_x.py", line 439, in dXdata
    try : field = int(block[s:e])
ValueError: invalid literal for int() with base 10: '0.000000'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
   File "C:\Program Files\Blender  Foundation\Blender\2.67\scripts\addons_contrib\io_directx_bel__init__.py",  line 211, in execute
    return import_x.load(self, context, **keywords)
  File "C:\Program Files\Blender Foundation\Blender\2.67\scripts\addons_contrib\io_directx_bel\import_x.py", line 943, in load
    import_dXtree(rootTokens)
   File "C:\Program Files\Blender  Foundation\Blender\2.67\scripts\addons_contrib\io_directx_bel\import_x.py",  line 695, in import_dXtree
    child = import_dXtree(getChilds(tokenname),lvl+1)
   File "C:\Program Files\Blender  Foundation\Blender\2.67\scripts\addons_contrib\io_directx_bel\import_x.py",  line 695, in import_dXtree
    child = import_dXtree(getChilds(tokenname),lvl+1)
   File "C:\Program Files\Blender  Foundation\Blender\2.67\scripts\addons_contrib\io_directx_bel\import_x.py",  line 648, in import_dXtree
    ob = getMesh(parentname,tokenname)
   File "C:\Program Files\Blender  Foundation\Blender\2.67\scripts\addons_contrib\io_directx_bel\import_x.py",  line 761, in getMesh
    nVerts, verts, nFaces, faces = readToken(tokenname)
   File "C:\Program Files\Blender  Foundation\Blender\2.67\scripts\addons_contrib\io_directx_bel\import_x.py",  line 400, in readToken
    fields, ptr = dXtemplateData(tpl,block)
   File "C:\Program Files\Blender  Foundation\Blender\2.67\scripts\addons_contrib\io_directx_bel\import_x.py",  line 420, in dXtemplateData
    datavalue, ptr = dXarray(block, datatype, length, ptr)
   File "C:\Program Files\Blender  Foundation\Blender\2.67\scripts\addons_contrib\io_directx_bel\import_x.py",  line 479, in dXarray
    datavalue, na = dXdata(block[s:e+1],datatype,1)
  File "C:\Program Files\Blender Foundation\Blender\2.67\scripts\addons_contrib\io_directx_bel\import_x.py", line 457, in dXdata
    fields, ptr = dXtemplateData(tpl,block,s)
   File "C:\Program Files\Blender  Foundation\Blender\2.67\scripts\addons_contrib\io_directx_bel\import_x.py",  line 424, in dXtemplateData
    datavalue, ptr = dXdata(block, datatype, length, ptr)
  File "C:\Program Files\Blender Foundation\Blender\2.67\scripts\addons_contrib\io_directx_bel\import_x.py", line 441, in dXdata
    e = block.index(',',s+1)
ValueError: substring not found

location: <unknown location>:-1
# 

it's just a teepot .x file exported by the same Blender 2.67 off.
Big problem "to divide by null" impossible with an integer, off'course!

**Comment by littleneo** [comment]
Hi,
I tested a few file with 2.67, I cant reproduce your error.
could you share your new.x teapot file ?
maybe check if the x file is encoded as ascii, not binary (not supported yet)
thanks,
Jerome
